/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 

import pojos.EPOC 
import pojos.Treatment
import pojos.PulmonaryCondition
import pojos.Asthma
import pojos.AsthmaStage 
import pojos.*;


rule "Chornic home oxygen therapy Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equals("Severe chronic hypoxemia"))
    then
        Treatment treatment = new Treatment();
        treatment.setTherapy("Chronic home oxygen therapy");
        p.addTreatment(treatment);
        System.out.println("Pulmonary condition: Severe chronic hypoxemia - Chornic home oxygen therapy is the best treatment for the patient");
end

rule "Bullectomy Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("Bulla"))
    then
        Treatment treatment = new Treatment();
        treatment.setTherapy("Bullectomy");
        p.addTreatment(treatment);
        System.out.println("Pulmonary condition: Bulla - Bullectomy is the best treatment for the patient");
end

rule "Pulmonar volume reduction Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("Severe heterogeneous emphysema in upper lobes"))
    then
        Treatment treatment = new Treatment();
        treatment.setTherapy("Pulmonar volume reduction");
        p.addTreatment(ConstantTreatments.TREATMENT1);
        System.out.println("Pulmonary condition: SEVERE HETEROGENEOUS EMPHYSEMA IN UPPER LOBES - Pulmonar volume reduction is the best treatment for the patient");
end

rule "Bronchoscopic intervention Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("Advanced emphysema"))
    then
        Treatment treatment = new Treatment();
        treatment.setTherapy("Bronchoscopic intervention");
        p.addTreatment(treatment);
        System.out.println("Pulmonary condition: ADVANCED EMPHYSEMA - Bronchoscopic intervention is the best treatment for the patient");
end

rule "Pulmonar transplant Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("Severe COPD"))
    then
        Treatment treatment = new Treatment();
        treatment.setTherapy("Pulmonar transplant");
        p.addTreatment(treatment);
        System.out.println("Pulmonary condition: SEVERE COPD - Pulmonar transplant is the best treatment for the patient");
end

rule "Influenza vaccine Rule"
    dialect "java"
    when 
        p: Patient (getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"),  influenza_vaccine == false)
    then 
        p.setInfluenza_vaccine(true);
        System.out.println("You should put influenza vaccine");
end

rule "Pneumonia vaccine Rule"
    dialect "java"
    when 
        p: Patient (getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), pneumonia_vaccine == false, age>65)
    then 
        p.setPneumonia_vaccine(true);
        System.out.println("You should put pneumonia vaccine");
end

rule "SABA/SAMA Rule"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), treatment_list.isEmpty() == true, hospitalization == false, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() <= 1, getEpoc().getCAT() < 10)
    then 
        Treatment treatment = new Treatment();
        treatment.setDrug("SABA/SAMA");
        treatment.setDose("2-4 inhalations/day");
        p.addTreatment(treatment);
        System.out.println("2-4 inhalations/day of SABA/SAMA is the best treatment for the patient");
end

rule "LABA/LAMA Rule"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), treatment_list.isEmpty() == true, hospitalization == false,  getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 10)
    then 
        Treatment treatment = new Treatment();
        treatment.setDrug("LABA/LAMA");
        treatment.setDose("1-2 inhalations/day");
        p.addTreatment(treatment);
        System.out.println("1-2 inhalations/day of LABA/LAMA is the best treatment for the patient");
end
rule "LAMA Rule 1"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), treatment_list.isEmpty() == true, hospitalization == true,  getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() <= 1, getEpoc().getCAT() < 10)
    then 
        Treatment treatment = new Treatment();
        treatment.setDrug("LAMA");
        treatment.setDose(" 1-2 inhalations/day ");
        p.addTreatment(treatment);
        System.out.println("1-2 inhalations/day of LAMA is the best treatment for the patient");
end

rule "LABA+IC Rule 1"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), treatment_list.isEmpty() == true, hospitalization == true, getString_comorbidities().contains("cardiovascular diseases") == false, getString_comorbidities().contains("pulmonar tuberculosis") == false, getString_comorbidities().contains("viral infection") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 10, getEpoc().isEosinophilia() == true)
    then 
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("IC");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day IC is the best treatment for the patient");
end

rule "LAMA Rule 2"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), treatment_list.isEmpty() == true, hospitalization == true, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 10, getEpoc().getCAT() < 20, getEpoc().isEosinophilia() == false)
    then 
        Treatment treatment = new Treatment();
        treatment.setDrug("LAMA");
        treatment.setDose("1-2 inhalations/day");
        p.addTreatment(treatment);
        System.out.println("1-2 inhalations/day of LAMA is the best treatment for the patient");
end

rule "LABA+LAMA Rule 1"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), treatment_list.isEmpty() == true, hospitalization == true, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 20, getEpoc().isEosinophilia() == false)
    then 
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("LAMA");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA is the best treatment for the patient");
end

rule "keep treatment Rule"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), symptoms_controlled == true, treatment_list.isEmpty() == false)
    then
        System.out.println("Continue with the same treatment");
end

rule "LABA+LAMA Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled == false, treatment_list.isEmpty() == false, string_treatments.contains("LABA/LAMA") == true, string_comorbidities.contains("disnea") == true, getString_comorbidities().contains("cardiovascular diseases") == false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("LAMA");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA is the best treatment for the patient");
end

rule "LABA+LAMA+IC Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty() == false, string_treatments.contains("LABA/LAMA") == true, string_comorbidities.contains("disnea") == true, string_comorbidities.contains("cardiovascular diseases") == false, string_comorbidities.contains("pulmonar tuberculosis") == false,  string_comorbidities.contains("viral infection") == false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("LAMA");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        Treatment treatment3 = new Treatment();
        treatment3.setDrug("IC");
        treatment3.setDose("1-2 inhalations/day");
        p.addTreatment(treatment3);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA and 1-2 inhalations/day of IC is the best treatment for the patient");
end

rule "Change device Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), symptoms_controlled==false, treatment_list.isEmpty() == false, string_treatments.contains("LABA") == true, string_treatments.contains("LAMA") == true, string_comorbidities.contains("disnea") == true)
    then
        System.out.println("Change device and investigate other causes");
end

rule "Change device Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), symptoms_controlled==false, treatment_list.isEmpty()==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("disnea")==true)
    then
        System.out.println("Change device and investigate other causes");
end

rule "LABA+IC Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, getEpoc().exacerbations == true, getEpoc().EOS >= 300 || (getEpoc().EOS >= 100 && getEpoc().exa == 2))
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("IC");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of IC is the best treatment for the patient");
end

rule "LABA+LAMA Rule 3"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, string_comorbidities.contains("cardiovascular diseases")==false, getEpoc().exacerbations == true, getEpoc().EOS < 300 || getEpoc().exa < 2)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("LAMA");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA is the best treatment for the patient");
end

rule "Azimotricine Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("vision disorders")==false, getEpoc().exacerbations == true, getEpoc().EOS < 100)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("Azimotricine");
        treatment.setDose("250 mg/day");
        p.addTreatment(treatment);
        System.out.println("250 mg/day of Azimotricine is the best treatment for the patient");
end

rule "Roflumilast Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty() == false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_comorbidities.contains("cardiovascular diseases")==false, getEpoc().exacerbations == true, getEpoc().EOS < 100, getEpoc().FEV < 50)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("Roflumilast");
        treatment.setDose("500 mcg/day");
        p.addTreatment(treatment);
        System.out.println("500 mcg/day of Roflumilast is the best treatment for the patient");
end

rule "Change device Rule 3"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, getEpoc().exacerbations == true, getEpoc().EOS < 100, getEpoc().FEV > 50)
    then
        System.out.println("Change device and investigate other causes");
end

rule "LABA+LAMA+IC Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_comorbidities.contains("cardiovascular diseases")==false, getEpoc().exacerbations == true, getEpoc().EOS > 100)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("LAMA");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        Treatment treatment3 = new Treatment();
        treatment3.setDrug("IC");
        treatment3.setDose("1-2 inhalations/day");
        p.addTreatment(treatment3);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA and 1-2 inhalations/day of IC is the best treatment for the patient");
end

rule "Azimotricine Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("vision disorders")==false, getEpoc().exacerbations == true, getEpoc().EOS > 100)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("Azimotricine");
        treatment.setDose("250 mg/day");
        p.addTreatment(treatment);
        System.out.println("250 mg/day of Azimotricine is the best treatment for the patient");
end

rule "Roflumilast Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, getEpoc().exacerbations == true, getEpoc().EOS > 100, getEpoc().FEV < 50)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("Roflumilast");
        treatment.setDose("500 mcg/day");
        p.addTreatment(treatment);
        System.out.println("500 mcg/day of Roflumilast is the best treatment for the patient");
end

rule "Change device Rule 4"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, getEpoc().exacerbations == true, getEpoc().EOS > 100, getEpoc().FEV > 50)
    then
        System.out.println("Change device and investigate other causes");
end

rule "LABA+LAMA+IC Rule 3"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), symptoms_controlled==false, treatment_list.isEmpty()==false, string_treatments.contains("LABA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, getEpoc().exacerbations == true)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("LABA");
        treatment1.setDose("1-2 inhalations/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("LAMA");
        treatment2.setDose("1-2 inhalations/day");
        p.addTreatment(treatment2);
        Treatment treatment3 = new Treatment();
        treatment3.setDrug("IC");
        treatment3.setDose("1-2 inhalations/day");
        p.addTreatment(treatment3);
        System.out.println("1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA and 1-2 inhalations/day of IC is the best treatment for the patient");
end


rule "Cardiovascular disease"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), string_comorbidities.contains("cardiovascular diseases")==true, string_comorbidities.contains("vision disorders")==false)
    then 
        Treatment treatment = new Treatment();
        treatment.setDrug("Azimotricine");
        treatment.setDose("250 mg/day");
        p.addTreatment(treatment);
        System.out.println("250 mg/day of Azimotricine is the best treatment for the patient");
end

rule "Vision disorders"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), string_comorbidities.contains("cardiovascular diseases")==true, string_comorbidities.contains("vision disorders")==true)
    then 
        Treatment treatment = new Treatment();
        treatment.setTherapy("Chronic home oxygen therapy");
        p.addTreatment(treatment);
        System.out.println("Chronic home oxygen therapy is the best treatment for the patient");
end

rule "Tuberculosis and Infection"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equals("NONE"), string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("viral infection")==true)
    then 
        Treatment treatment = new Treatment();
        treatment.setDrug("Muscarinic receptor antagonists");
        treatment.setDose("18 mcg/day");
        p.addTreatment(treatment);
        System.out.println("18 mcg/day of Muscarinic receptor antagonists is the best treatment for the patient");
        
end
rule "No medication 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage == 1, symptoms_controlled==true)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("No medication");
        treatment.setDose("None");
        p.addTreatment(treatment);
        System.out.println("It is recommended not consume any control medication");
end

rule "No medication 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage== 2, symptoms_controlled==true)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("No medication");
        treatment.setDose("None");
        p.addTreatment(treatment);
        p.setTreatment_stage(1);
        System.out.println("It is recommended not consume any control medication");
end

rule "No medication 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true, treat_stage==2, symptoms_controlled==true, age > 5, string_comorbidities.contains("hypertension")==false, getAsthma().dayTimeSymptoms_w < 2, getAsthma().rescueMedication_w < 2, getAsthma().nocturnalSymptoms_w < 1, getAsthma().limitations==0, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y==0)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("No medication");
        treatment.setDose("None");
        p.addTreatment(treatment);
        p.setTreatment_stage(1);
        p.getAsthma().setStage_string("Intermittent");
        System.out.println("Disease Stage : INTERMITTENT ASTHMA - It is recommended not consume any control medication");
end

rule "GCI low dosis 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true, treat_stage==1, age <5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.1 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.1 mg/day of GCI is the best treatment for the patient");
end

rule "GCI low dosis 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==1, age >5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.2 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.2 mg/day of GCI is the best treatment for the patient");
end

rule "GCI low dosis 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age <5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.1 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.1 mg/day of GCI is the best treatment for the patient");
end

rule "GCI low dosis 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.2 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.2 mg/day of GCI is the best treatment for the patient");
end

rule "GCI low dosis 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w > 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.1 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("Mild persistent");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - 0.1 mg/day of GCI is the best treatment for the patient");
end

rule "GCI low dosis 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w > 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.2 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("Mild persistent");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - 0.2 mg/day of GCI is the best treatment for the patient");
end


rule "GCI medium dosis 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==2, age <5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.2 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(3);
        System.out.println("0.2 mg/day of GCI is the best treatment for the patient");
end

rule "GCI medium dosis 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==2, age >5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.3- 0.4mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(3);
        System.out.println("0.3-0.4 mg/day of GCI is the best treatment for the patient");
end

rule "GCI medium dosis 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age <5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.2 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(3);
        System.out.println("0.2 mg/day of GCI is the best treatment for the patient");
end


rule "GCI medium dosis 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.3-0.4mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(3);
        System.out.println("0.3-0.4 mg/day of GCI is the best treatment for the patient");
end

rule "GCI medium dosis 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 6, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 6, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w > 3, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.2 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage: MODERATE PERSISTENT ASTHMA - 0.2 mg/day of GCI is the best treatment for the patient");
end

rule "GCI medium dosis 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty() == true,  age > 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 6, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 6, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w > 3, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function > 60, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.3-0.4 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage : MODERATE PERSISTENT ASTHMA - 0.3-0.4 mg/day of GCI is the best treatment for the patient");
end

rule "GCI high dosis + ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age <5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular diseases")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(5);
        System.out.println("0.4 mg/day of GCI combined with 0.02 mg/day of ARLT and is the best treatment for the patient");
end

rule "GCI high dosis + ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==6, age <5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular diseases")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(5);
        System.out.println("0.4 mg/day of GCI combined with 0.02 mg/day of ARLT and is the best treatment for the patient");
end

rule "GCI high dosis + BAAL 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age > 5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.5 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(5);
        System.out.println("0.5 mg/day of GCI combined with 0.05 mg/day of BAAL and is the best treatment for the patient");
end

rule "GCI high dosis + BAAL 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==6, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.5 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(5);
        System.out.println("0.5 mg/day of GCI combined with 0.05 mg/day of BAAL and is the best treatment for the patient");
end

rule "GCI high dosis 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 8, getAsthma().rescueMedication_w > 8, getAsthma().nocturnalSymptoms_w > 6, getAsthma().limitations==3, getAsthma().pulmonar_function < 60, getAsthma().exarcebations_y>2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.6 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("Disease Stage : SEVERE PERSISTENT ASTHMA - 0.6 mg/day of GCI is the best treatment for the patient");
end

rule "GCI high dosis 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 8, getAsthma().rescueMedication_w > 8, getAsthma().nocturnalSymptoms_w > 6, getAsthma().limitations==3, getAsthma().pulmonar_function < 60, getAsthma().exarcebations_y>2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCI");
        treatment.setDose("0.5 mg/day GCI");
        p.addTreatment(treatment);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("Disease Stage : SEVERE PERSISTENT ASTHMA - 0.5 mg/day of GCI is the best treatment for the patient");
end

rule "ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==1, age <5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("ARLT");
        treatment.setDose("0.02 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==1, age >5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("ARLT");
        treatment.setDose("0.04 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "ARLT 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age <5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("ARLT");
        treatment.setDose("0.02 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "ARLT 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("ARLT");
        treatment.setDose("0.04 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        System.out.println("0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "ARLT 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false, getAsthma().dayTimeSymptoms_w > 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w > 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("ARLT");
        treatment.setDose("0.02 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("Mild persistent");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - 0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "ARLT 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false, getAsthma().dayTimeSymptoms_w > 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w > 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("ARLT");
        treatment.setDose("0.04 mg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("Mild persistent");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - 0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI low dosis + ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==2, age <5, symptoms_controlled==false, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.1 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(3);
        System.out.println("0.1 mg/day of GCI combined with 0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI low dosis + ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==2, age >5, symptoms_controlled==false, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.04 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(3);
        System.out.println("0.2 mg/day of GCI combined with 0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI low dosis + ARLT 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age >5, symptoms_controlled==true, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.04 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(3);
        System.out.println("0.2 mg/day of GCI combined with 0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI low dosis + ARLT 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age <5, symptoms_controlled==true, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.1 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(3);
        System.out.println("0.1 mg/day of GCI combined with 0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI low dosis + BAAL 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==2, age >5, symptoms_controlled==false, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true || string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(3);
        System.out.println("0.2 mg/day of GCI combined with 0.05 mg/day of BAAL is the best treatment for the patient");
end

rule "GCI low dosis + BAAL 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==4, age >5, symptoms_controlled==true, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true || string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(3);
        System.out.println("0.2 mg/day of GCI combined with 0.05 mg/day of BAAL is the best treatment for the patient");
end

rule "GCI low dosis + BAAL 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true || string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false, getAsthma().dayTimeSymptoms_w > 6, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 6, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w > 3, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function > 60, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>2)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage : MODERATE PERSISTENT ASTHMA - 0.2 mg/day of GCI combined with 0.05 mg/day of BAAL is the best treatment for the patient");
end

rule "GCI low dosis + ARLT 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false, getAsthma().dayTimeSymptoms_w > 6, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 6, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w > 3, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function > 60, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>2)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.1 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage :MODERATE PERSISTENT ASTHMA - 0.1 mg/day of GCI combined with 0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI low dosis + ARLT 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false, getAsthma().dayTimeSymptoms_w > 6, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 6, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w > 3, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function > 60, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>2)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.04 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage : MODERATE PERSISTENT ASTHMA - 0.2 mg/day of GCI combined with 0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI medium dosis + BAAL 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false, getAsthma().dayTimeSymptoms_w > 8, getAsthma().rescueMedication_w > 8, getAsthma().nocturnalSymptoms_w > 6, getAsthma().limitations==3, getAsthma().pulmonar_function < 60, getAsthma().exarcebations_y>2)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.3-0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(5);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("Disease Stage : SEVERE PERSISTENT ASTHMA - 0.3-0.4 mg/day of GCI combined with 0.05 mg/day of BAAL is the best treatment for the patient");
end

rule "GCI medium dosis + ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age >5,symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.3-0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.04 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        System.out.println("0.3-0.4 mg/day of GCI combined with 0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI medium dosis + ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age <5,symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        System.out.println("0.2 mg/day of GCI combined with 0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI medium dosis + ARLT 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==5, age <5,symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.2 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.02 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        System.out.println("0.2 mg/day of GCI combined with 0.02 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI medium dosis + ARLT 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==5, age >5,symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.3-0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("ARLT");
        treatment2.setDose("0.04 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        System.out.println("0.3-0.4 mg/day of GCI combined with 0.04 mg/day of ARLT is the best treatment for the patient");
end

rule "GCI medium dosis + BAAL 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==3, age >5,symptoms_controlled==false, string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.3-0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        System.out.println("0.3-0.4 mg/day of GCI combined with 0.05 mg/day of BAAL is the best treatment for the patient");
end

rule "GCI medium dosis + BAAL 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==5, age >5,symptoms_controlled==true, string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("GCI");
        treatment1.setDose("0.3-0.4 mg/day");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("BAAL");
        treatment2.setDose("0.05 mg/day");
        p.addTreatment(treatment2);
        p.setTreatment_stage(4);
        System.out.println("0.3-0.4 mg/day of GCI combined with 0.05 mg/day of BAAL is the best treatment for the patient");
end

rule "GCO 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==5, age <5, symptoms_controlled==false, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCO");
        treatment.setDose("0.5-2 mg/kg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(6);
        System.out.println("0.5-2 mg/kg/day of GCO is the best treatment for the patient");
end

rule "GCO 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==5, age>5, symptoms_controlled==false, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("GCO");
        treatment.setDose("40-60 mg/kg/day");
        p.addTreatment(treatment);
        p.setTreatment_stage(6);
        System.out.println("40-60 mg/kg/day of GCO is the best treatment for the patient");
end

rule "BAAC 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, getAsthma().PS>0, getAsthma().PS<3, getAsthma().PEF<80, getAsthma().SAT_O2<94)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("BAAC");
        treatment.setDose("0.15-2.5 mg/kg on demand");
        p.addTreatment(treatment);
        System.out.println("0.15-2.5 mg/kg of BAAC on demand is the best treatment for the patient");
end

rule "BAAC 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, getAsthma().PS>0, getAsthma().PS<3, getAsthma().PEF<80, getAsthma().SAT_O2<94)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("BAAC");
        treatment.setDose("0.5-1 mg/kg on demand");
        p.addTreatment(treatment);
        System.out.println("0.5-1 mg/kg of BAAC on demand is the best treatment for the patient");
end

rule "BAAC + Sistemic Corticoids 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), treatment_list.isEmpty()==true,  age < 5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false,
        string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, getAsthma().PS>4, getAsthma().PS<6, getAsthma().PEF<80, getAsthma().SAT_O2>91, getAsthma().SAT_O2<94)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("BAAC");
        treatment1.setDose("0.15-2.5 mg/kg");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("Sistemic corticoids");
        treatment2.setDose("1 mg/kg/day");
        p.addTreatment(treatment2);
        System.out.println("0.15-2.5 mg/kg of BAAC combined with 1 mg/kg/day of Sistemic Corticoidsis is the best treatment for the patient");
end

rule "BAAC + Sistemic Corticoids 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), treatment_list.isEmpty()==true,  age >5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, 
        string_comorbidities.contains("hypertiroidism")==false, string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, getAsthma().PS>4, getAsthma().PS<6, getAsthma().PEF>60, getAsthma().SAT_O2>91, getAsthma().SAT_O2<94)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("BAAC");
        treatment1.setDose("0.5-1 mg on demand");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("Sistemic corticoids");
        treatment2.setDose("3 mg/kg/day");
        p.addTreatment(treatment2);
        System.out.println("0.5-1 mg of BAAC on demand combined with 3 mg/kg/day of Sistemic Corticoidsis is the best treatment for the patient");
end

rule "BAAC + Sistemic Corticoids + Suplementary O2 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), treatment_list.isEmpty()==true, age >5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, 
        string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, getAsthma().PS>7, getAsthma().PS<9, getAsthma().PEF<60, getAsthma().SAT_O2<91)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("BAAC");
        treatment1.setDose("0.5-1 mg on demand");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("Sistemic corticoids");
        treatment2.setDose("3 mg/kg/day");
        p.addTreatment(treatment2);
        Treatment treatment3 = new Treatment();
        treatment3.setDrug("Suplementary O2");
        treatment3.setDose("On demand");
        p.addTreatment(treatment3);
        System.out.println("0.5-1 mg of BAAC on demand combined with 3 mg/kg/day of Sistemic Corticoidsis and Suplementary O2 on demand is the best treatment for the patient");
end

rule "BAAC + Sistemic Corticoids + Suplementary O2 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), treatment_list.isEmpty()==true, age <5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, 
        string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, 
        getAsthma().PS>7, getAsthma().PS<9, getAsthma().PEF<60, getAsthma().SAT_O2<91)
    then
        Treatment treatment1 = new Treatment();
        treatment1.setDrug("BAAC");
        treatment1.setDose("0.15-2.5 mg/kg");
        p.addTreatment(treatment1);
        Treatment treatment2 = new Treatment();
        treatment2.setDrug("Sistemic corticoids");
        treatment2.setDose("1 mg/kg/day");
        p.addTreatment(treatment2);
        Treatment treatment3 = new Treatment();
        treatment3.setDrug("Suplementary O2");
        treatment3.setDose("On demand");
        p.addTreatment(treatment3);
        System.out.println("0.15-2.5 mg/kg of BAAC combined with 1 mg/kg/day of Sistemic Corticoidsis and Suplementary O2 on demand is the best treatment for the patient");
end

rule "BAAC on demand Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string.equals("NONE"), string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false)
    then
        Treatment treatment = new Treatment();
        treatment.setDrug("BAAC");
        treatment.setDose("2-4 inhalations on demand during crisis");
        p.addTreatment(treatment);
        System.out.println("2-4 inhalations of BAAC on demand during a crisis is the best treatment");
end

rule "Hospitalization Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage==6, symptoms_controlled==false)
    then
        p.setHospitalization(true);
        System.out.println("The patient needs to be hospitalized");
end