/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 

import pojos.EPOC 
import pojos.Treatment
import pojos.PulmonaryCondition
import pojos.Asthma
import pojos.AsthmaStage 
import pojos.*;


rule "Chornic home oxygen therapy Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("Severe chronic hypoxemia")==true)
        t: Treatment(getDrug().equalsIgnoreCase("BAAL"))
then
       
        p.addTreatment(Treatment.CHRONIC_OXIGEN_THERAPY);
        System.out.println("Pulmonary condition: Severe chronic hypoxemia - The patient has to be treated with Chronic home oxygen therapy, defense of the practice ");
end

rule "Bullectomy Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("Bulla")==true)
    then
        
        p.addTreatment(Treatment.BULLECTOMY);
        System.out.println("Pulmonary condition: Bulla - The patient has to be treated with Bullectomy ");
end

rule "Pulmonar volume reduction Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("Severe heterogeneous emphysema in upper lobes")==true)
    then
        
        p.addTreatment(Treatment.PULMONAR_VOLUME_REDUCTION);
        System.out.println("Pulmonary condition: SEVERE HETEROGENEOUS EMPHYSEMA IN UPPER LOBES - The patient has to be treated with Pulmonar volume reduction");
end

rule "Bronchoscopic intervention Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("Advanced emphysema")==true)
    then
        
        p.addTreatment(Treatment.BRONCHOSCOPIC_INTERVENTION);
        System.out.println("Pulmonary condition: ADVANCED EMPHYSEMA - The patient has to be treated with Bronchoscopic intervention ");
end

rule "Pulmonar transplant Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("Severe COPD")==true)
    then
        
        p.addTreatment(Treatment.PULMONAR_TRANSPLANT);
        System.out.println("Pulmonary condition: SEVERE COPD - The patient has to be treated with Pulmonar transplant");
end

rule "Influenza vaccine Rule"
    dialect "java"
    when 
        p: Patient (getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true,  influenza_vaccine == false)
    then 
        p.setInfluenza_vaccine(true);
        p.addTreatment(Treatment.INFLUENZAV);
        System.out.println("You should put influenza vaccine");
end

rule "Pneumonia vaccine Rule"
    dialect "java"
    when 
        p: Patient (getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, pneumonia_vaccine == false, age>65)
    then 
        p.setPneumonia_vaccine(true);
        p.addTreatment(Treatment.PNEUMONIAV);
        System.out.println("You should put pneumonia vaccine");
end

rule "SABA/SAMA Rule"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, treatment_list.isEmpty() == true, hospitalization == false, getEpoc().getExa()<=1, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() <= 1, getEpoc().getCAT() < 10)
    then 
        p.addTreatment(Treatment.SABA_SAMA);
        System.out.println("The patient has to be treated with 2-4 inhalations/day of SABA/SAMA");
end

rule "LABA/LAMA Rule"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, treatment_list.isEmpty() == true, hospitalization == false, getEpoc().getExa()<2, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 10)
    then 
        
        p.addTreatment(Treatment.LABA_LAMA);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA/LAMA");
end
rule "LAMA Rule 1"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, treatment_list.isEmpty() == true, hospitalization == false, getEpoc().getExa()>1, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() <= 1, getEpoc().getCAT() < 10)
    then 
        
        p.addTreatment(Treatment.LAMA);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LAMA");
end

rule "LABA+IC Rule 1"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE"), treatment_list.isEmpty() == true, hospitalization == false,getEpoc().getExa()>1, getString_comorbidities().contains("cardiovascular diseases") == false, getString_comorbidities().contains("pulmonar tuberculosis") == false, getString_comorbidities().contains("viral infection") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 10, getEpoc().isEosinophilia() == true)
    then 
       
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.IC);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day IC ");
end

rule "LAMA Rule 2"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equalsIgnoreCase("NONE"), treatment_list.isEmpty() == true, hospitalization == false, getEpoc().getExa()>1,getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 10, getEpoc().getCAT() < 20, getEpoc().isEosinophilia() == false)
    then 
        
        p.addTreatment(Treatment.LAMA);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LAMA");
end

rule "LABA+LAMA Rule 1"
    dialect "java"
    when 
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equalsIgnoreCase("NONE"), treatment_list.isEmpty() == true, hospitalization == false, getEpoc().getExa()>1, getString_comorbidities().contains("cardiovascular diseases") == false, getEpoc().getmMRC() > 1, getEpoc().getCAT() > 20, getEpoc().isEosinophilia() == false)
    then 
        
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.LAMA);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA");
end

rule "keep treatment Rule"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), symptoms_controlled == true, treatment_list.isEmpty() == false)
    then
        System.out.println("Continue with the same treatment");
end

rule "LABA+LAMA Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equalsIgnoreCase("NONE"), symptoms_controlled == false, treatment_list.isEmpty() == false, string_treatments.contains("LABA/LAMA") == true, getEpoc().isDisnea() == true, getString_comorbidities().contains("cardiovascular diseases") == false)
    then
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.LAMA);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA ");
end

rule "LABA+LAMA+IC Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string.equalsIgnoreCase("NONE"), symptoms_controlled==false, treatment_list.isEmpty() == false, string_treatments.contains("LABA/LAMA") == true, getEpoc().isDisnea() == true, string_comorbidities.contains("cardiovascular diseases") == false, string_comorbidities.contains("pulmonar tuberculosis") == false,  string_comorbidities.contains("viral infection") == false)
    then
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.LAMA);
        p.addTreatment(Treatment.IC);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA and 1-2 inhalations/day of IC");
end

rule "Change device Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), symptoms_controlled==false, treatment_list.isEmpty() == false, string_treatments.contains("LABA") == true, string_treatments.contains("LAMA") == true, getEpoc().isDisnea() == true)
    then
        System.out.println("Change device and investigate other causes");
end

rule "Change device Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), symptoms_controlled==false, treatment_list.isEmpty()==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, getEpoc().isDisnea() == true)
    then
        System.out.println("Change device and investigate other causes");
end

rule "LABA+IC Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, getEpoc().isDisnea() == false, getEpoc().EOS >= 300 || (getEpoc().EOS >= 100 && getEpoc().exa == 2))
    then
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.IC);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of IC ");
end

rule "LABA+LAMA Rule 3"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, string_comorbidities.contains("cardiovascular diseases")==false, getEpoc().isDisnea() == false, getEpoc().EOS < 300 || getEpoc().exa < 2)
    then
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.LAMA);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA ");
end

rule "Azimotricine Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("vision disorders")==false,getEpoc().isDisnea() == false, getEpoc().EOS < 100)
    then
        
        p.addTreatment(Treatment.AZIMOTRICINE);
        System.out.println("The patient has to be treated with 250 mg/day of Azimotricine");
end

rule "Roflumilast Rule 1"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty() == false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_comorbidities.contains("cardiovascular diseases")==false, getEpoc().isDisnea() == false, getEpoc().EOS < 100, getEpoc().FEV < 50)
    then
        
        p.addTreatment(Treatment.ROFLUMILAST);
        System.out.println("The patient has to be treated with 500 mcg/day of Roflumilast");
end

rule "Change device Rule 3"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, getEpoc().isDisnea() == false, getEpoc().EOS < 100, getEpoc().FEV > 50)
    then
        System.out.println("Change device and investigate other causes");
end

rule "LABA+LAMA+IC Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_comorbidities.contains("cardiovascular diseases")==false, getEpoc().isDisnea() == false, getEpoc().EOS > 100)
    then
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.LAMA);
        p.addTreatment(Treatment.IC);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA and 1-2 inhalations/day of IC");
end

rule "Azimotricine Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==false, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("vision disorders")==false, getEpoc().isDisnea() == false, getEpoc().EOS > 100)
    then
        p.addTreatment(Treatment.AZIMOTRICINE);
        System.out.println("The patient has to be treated with 250 mg/day of Azimotricine ");
end

rule "Roflumilast Rule 2"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, getEpoc().isDisnea() == false, getEpoc().EOS > 100, getEpoc().FEV < 50)
    then
        p.addTreatment(Treatment.ROFLUMILAST);
        System.out.println("The patient has to be treated with 500 mcg/day of Roflumilast");
end

rule "Change device Rule 4"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, smoker==true, string_treatments.contains("LABA")==true, string_treatments.contains("LAMA")==true, string_treatments.contains("IC")==true,getEpoc().isDisnea() == false, getEpoc().EOS > 100, getEpoc().FEV > 50)
    then
        System.out.println("Change device and investigate other causes");
end

rule "LABA+LAMA+IC Rule 3"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, symptoms_controlled==false, treatment_list.isEmpty()==false, string_treatments.contains("LABA")==true, string_treatments.contains("IC")==true, string_comorbidities.contains("cardiovascular diseases")==false, string_comorbidities.contains("pulmonar tuberculosis")==false,  string_comorbidities.contains("viral infection")==false, getEpoc().isDisnea() == false)
    then
        p.addTreatment(Treatment.LABA);
        p.addTreatment(Treatment.LAMA);
        p.addTreatment(Treatment.IC);
        System.out.println("The patient has to be treated with 1-2 inhalations/day of LABA combined with 1-2 inhalations/day of LAMA and 1-2 inhalations/day of IC");
end


rule "Cardiovascular disease"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("vision disorders")==false)
    then 
        p.addTreatment(Treatment.AZIMOTRICINE);
        System.out.println("The patient has to be treated with 250 mg/day of Azimotricine ");
end

rule "Vision disorders"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("vision disorders")==true)
    then 
        p.addTreatment(Treatment.CHRONIC_OXIGEN_THERAPY);
        System.out.println("The patient has to be treated with Chronic home oxygen therapy");
end

rule "Tuberculosis and Infection"
    dialect "java"
    when
        p: Patient(getRespiratorydisease().equals("EPOC"), getEpoc().getCondition_string().equalsIgnoreCase("NONE")==true, string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("viral infection")==true)
    then 
        
        p.addTreatment(Treatment.MUSC_ANTAGONISTS);
        System.out.println("The patient has to be treated with 18 mcg/day of Muscarinic receptor antagonists");
        
end
rule "No medication 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, treat_stage == 1, getAsthma().getStage_string().equalsIgnoreCase("INTERMITTENT")==true, symptoms_controlled==true)
    then
        
        p.addTreatment(Treatment.NO_MED);
        System.out.println("It is recommended not consume any control medication");
end

rule "No medication 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true, treat_stage== 2, symptoms_controlled==true)
    then
        p.addTreatment(Treatment.NO_MED);
        p.setTreatment_stage(1);
        p.getAsthma().setStage_string("Intermittent");
        System.out.println("It is recommended not consume any control medication");
end

rule "No medication 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true, getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,  age > 5, string_comorbidities.contains("hypertension")==false, getAsthma().dayTimeSymptoms_w < 2, getAsthma().rescueMedication_w < 2, getAsthma().nocturnalSymptoms_w < 1, getAsthma().limitations==0, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y==0)
    then
        p.addTreatment(Treatment.NO_MED);
        p.setTreatment_stage(1);
        p.getAsthma().setStage_string("INTERMITTENT");
        System.out.println("Disease Stage : INTERMITTENT ASTHMA - It is recommended not consume any control medication");
end

rule "GCI low dosis 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false,getAsthma().getStage_string().equalsIgnoreCase("INTERMITTENT")==true, treat_stage==1, age <=5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        
        p.addTreatment(Treatment.GCI_LOW_C);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.1 mg/day of GCI");
end

rule "GCI low dosis 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false,getAsthma().getStage_string().equalsIgnoreCase("INTERMITTENT")==true,treat_stage==1, age >5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        
        p.addTreatment(Treatment.GCI_LOW_A);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI");
end

rule "GCI low dosis 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false,getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true, treat_stage==3, age <=5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_C);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.1 mg/day of GCI");
end

rule "GCI low dosis 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true, treat_stage==3, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        p.setTreatment_stage(2);
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI");
end

rule "GCI low dosis 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,  age <= 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w >= 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w >= 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        p.addTreatment(Treatment.GCI_LOW_C);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - The patient has to be treated with 0.1 mg/day of GCI ");
end

rule "GCI low dosis 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true, getAsthma().getStage_string().equalsIgnoreCase("NONE")==true, age > 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w >= 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w >= 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - The patient has to be treated with 0.2 mg/day of GCI");
end


rule "GCI medium dosis 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true, treat_stage==2, age <=5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
       
        p.addTreatment(Treatment.GCI_MED_C);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI ");
end

rule "GCI medium dosis 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==2, age >5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.3-0.4 mg/day of GCI");
end

rule "GCI medium dosis 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==4, age <=5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        p.addTreatment(Treatment.GCI_MED_C);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI");
end


rule "GCI medium dosis 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treat_stage==4, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.3-0.4 mg/day of GCI ");
end

rule "GCI medium dosis 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("NONE")==true, treatment_list.isEmpty()==true,  age <= 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w > 3, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 3, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w >=2, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>=2)
    then
        p.addTreatment(Treatment.GCI_MED_C);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage: MODERATE PERSISTENT ASTHMA - The patient has to be treated with 0.2 mg/day of GCI ");
end

rule "GCI medium dosis 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("NONE")==true, treatment_list.isEmpty() == true,  age > 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, 
getAsthma().dayTimeSymptoms_w > 3, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 3, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w >=2, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>=2)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage : MODERATE PERSISTENT ASTHMA - The patient has to be treated with 0.3-0.4 mg/day of GCI ");
end

rule "GCI high dosis + ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==4, age <=5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        
        p.addTreatment(Treatment.GCI_HIGH_C);
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(5);
        System.out.println("The patient has to be treated with 0.4 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI high dosis + ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==6, age <=5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_HIGH_C);
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(5);
        System.out.println("The patient has to be treated with 0.4 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI high dosis + BAAL 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==4, age > 5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        p.addTreatment(Treatment.GCI_HIGH_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(5);
        System.out.println("The patient has to be treated with 0.5 mg/day of GCI combined with 0.05 mg/day of BAAL ");
end

rule "GCI high dosis + BAAL 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==6, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        p.addTreatment(Treatment.GCI_HIGH_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(5);
        System.out.println("The patient has to be treated with 0.5 mg/day of GCI combined with 0.05 mg/day of BAAL");
end

rule "GCI high dosis 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("NONE")==true, treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, getAsthma().dayTimeSymptoms_w >= 8, getAsthma().rescueMedication_w >= 6, getAsthma().nocturnalSymptoms_w >= 6, getAsthma().limitations==3, getAsthma().pulmonar_function < 60, getAsthma().exarcebations_y>2)
    then
        p.addTreatment(Treatment.GCI_HIGH_A);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("Disease Stage : SEVERE PERSISTENT ASTHMA - The patient has to be treated with 0.5 mg/day of GCI");
end

rule "GCI high dosis 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,treatment_list.isEmpty()==true,  age <= 5, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, 
getAsthma().dayTimeSymptoms_w >= 8, getAsthma().rescueMedication_w >= 6, getAsthma().nocturnalSymptoms_w >= 6, getAsthma().limitations==3, getAsthma().pulmonar_function < 60, getAsthma().exarcebations_y>2)
    then
        p.addTreatment(Treatment.GCI_HIGH_C);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("Disease Stage : SEVERE PERSISTENT ASTHMA - The patient has to be treated with 0.4 mg/day of GCI ");
end

rule "ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("INTERMITTENT")==true,treat_stage==1, age <=5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.02 mg/day of ARLT ");
end

rule "ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("INTERMITTENT")==true,treatment_list.isEmpty()==false, treat_stage==1, age >5, symptoms_controlled==false, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.04 mg/day of ARLT");
end

rule "ARLT 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true,treat_stage==3, age <=5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.02 mg/day of ARLT ");
end

rule "ARLT 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true,treat_stage==3, age >5, symptoms_controlled==true, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("The patient has to be treated with 0.04 mg/day of ARLT ");
end

rule "ARLT 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true, getAsthma().getStage_string().equalsIgnoreCase("NONE")==true, age <= 5, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false, getAsthma().dayTimeSymptoms_w >= 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w >= 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - The patient has to be treated with 0.02 mg/day of ARLT ");
end

rule "ARLT 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==true,  getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,age > 5, string_comorbidities.contains("viral infection")==true || string_comorbidities.contains("pulmonary tuberculosis")==true, string_comorbidities.contains("cardiovascular disease")==false, getAsthma().dayTimeSymptoms_w >= 2, getAsthma().dayTimeSymptoms_w < 4, getAsthma().rescueMedication_w >= 2, getAsthma().rescueMedication_w < 4, getAsthma().nocturnalSymptoms_w >= 1, getAsthma().nocturnalSymptoms_w < 2, getAsthma().limitations==1, getAsthma().pulmonar_function > 80, getAsthma().exarcebations_y>=0, getAsthma().exarcebations_y<2)
    then
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(2);
        p.getAsthma().setStage_string("MILD PERSISTENT");
        System.out.println("Disease Stage : MILD PERSISTENT ASTHMA - The patient has to be treated with 0.04 mg/day of ARLT ");
end

rule "GCI low dosis + ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false,getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true, treat_stage==2, age <=5, symptoms_controlled==false, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_C);
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.1 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI low dosis + ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true,treat_stage==2, age >5, symptoms_controlled==false, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI combined with 0.04 mg/day of ARLT");
end

rule "GCI low dosis + ARLT 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false,getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treat_stage==4, age >5, symptoms_controlled==true, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI combined with 0.04 mg/day of ARLT ");
end

rule "GCI low dosis + ARLT 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==4, age <=5, symptoms_controlled==true, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_C);
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.1 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI low dosis + BAAL 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==2, age >5, symptoms_controlled==false, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true || string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI combined with 0.05 mg/day of BAAL ");
end

rule "GCI low dosis + BAAL 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==4, age >5, symptoms_controlled==true, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true || string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("MODERATE PERSISTENT");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI combined with 0.05 mg/day of BAAL ");
end

rule "GCI low dosis + BAAL 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true || string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false, 
getAsthma().dayTimeSymptoms_w > 3, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 3, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w >=2, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>=2)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage : MODERATE PERSISTENT ASTHMA - The patient has to be treated with 0.2 mg/day of GCI combined with 0.05 mg/day of BAAL ");
end

rule "GCI low dosis + ARLT 5"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,treatment_list.isEmpty()==true,  age <= 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false, 
getAsthma().dayTimeSymptoms_w > 3, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 3, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w >=2, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>=2)
    then
        p.addTreatment(Treatment.GCI_LOW_C);
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage :MODERATE PERSISTENT ASTHMA - The patient has to be treated with 0.1 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI low dosis + ARLT 6"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false, 
getAsthma().dayTimeSymptoms_w > 3, getAsthma().dayTimeSymptoms_w < 8, getAsthma().rescueMedication_w > 3, getAsthma().rescueMedication_w < 8, getAsthma().nocturnalSymptoms_w >=2, getAsthma().nocturnalSymptoms_w < 6, getAsthma().limitations==2, getAsthma().pulmonar_function < 80, getAsthma().exarcebations_y>=2)
    then
        p.addTreatment(Treatment.GCI_LOW_A);
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(3);
        p.getAsthma().setStage_string("Moderate persistent");
        System.out.println("Disease Stage : MODERATE PERSISTENT ASTHMA - The patient has to be treated with 0.2 mg/day of GCI combined with 0.04 mg/day of ARLT ");
end

rule "GCI medium dosis + BAAL 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("NONE")==true,treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("HSS axis diseases")==true || string_comorbidities.contains("Decreased bone mineral density")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false, 
getAsthma().dayTimeSymptoms_w >= 8, getAsthma().rescueMedication_w >= 6, getAsthma().nocturnalSymptoms_w >= 6, getAsthma().limitations==3, getAsthma().pulmonar_function < 60, getAsthma().exarcebations_y>2)
   
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("Disease Stage : SEVERE PERSISTENT ASTHMA - The patient has to be treated with 0.3-0.4 mg/day of GCI combined with 0.05 mg/day of BAAL ");
end

rule "GCI medium dosis + ARLT 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==3, age >5,symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("The patient has to be treated with 0.3-0.4 mg/day of GCI combined with 0.04 mg/day of ARLT ");
end

rule "GCI medium dosis + ARLT 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==3, age <=5,symptoms_controlled==false, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_MED_C);
        p.addTreatment(Treatment.ARLT_C);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI medium dosis + ARLT 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==5, age <=5,symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_MED_C);
        p.addTreatment(Treatment.ARLT_C);;
        p.setTreatment_stage(4);
        System.out.println("The patient has to be treated with 0.2 mg/day of GCI combined with 0.02 mg/day of ARLT ");
end

rule "GCI medium dosis + ARLT 4"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==5, age >5,symptoms_controlled==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.addTreatment(Treatment.ARLT_A);
        p.setTreatment_stage(4);
        System.out.println("The patient has to be treated with 0.3-0.4 mg/day of GCI combined with 0.04 mg/day of ARLT ");
end

rule "GCI medium dosis + BAAL 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"),getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==3, age >5,symptoms_controlled==false, string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(4);
        p.getAsthma().setStage_string("Severe persistent");
        System.out.println("The patient has to be treated with 0.3-0.4 mg/day of GCI combined with 0.05 mg/day of BAAL");
end

rule "GCI medium dosis + BAAL 3"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treatment_list.isEmpty()==false, treat_stage==5, age >5,symptoms_controlled==true, string_comorbidities.contains("cardiovascular disease")==true, string_comorbidities.contains("viral infection")==false, string_comorbidities.contains("pulmonary tuberculosis")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("urinary retention")==false)
    then
        p.addTreatment(Treatment.GCI_MED_A);
        p.addTreatment(Treatment.BAAL);
        p.setTreatment_stage(4);
        System.out.println("The patient has to be treated with 0.3-0.4 mg/day of GCI combined with 0.05 mg/day of BAAL ");
end

rule "GCO 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==5, age <5, symptoms_controlled==false, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        
        p.addTreatment(Treatment.GCO_C);
        p.setTreatment_stage(6);
        System.out.println("The patient has to be treated with 0.5-2 mg/kg/day of GCO ");
end

rule "GCO 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, treatment_list.isEmpty()==false, treat_stage==5, age>5, symptoms_controlled==false, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("cardiovascular disease")==false)
    then
        p.addTreatment(Treatment.GCO_A);
        p.setTreatment_stage(6);
        System.out.println("The patient has to be treated with 40-60 mg/kg/day of GCO ");
end

rule "BAAC 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("CRISIS")==true, treatment_list.isEmpty()==true,  age <= 5, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, getAsthma().PS>0, getAsthma().PS<3, getAsthma().PEF<80, getAsthma().SAT_O2<94)
    then
        
        p.addTreatment(Treatment.BAAC_C);
        System.out.println("The patient has to be treated with 0.15-2.5 mg/kg of BAAC on demand ");
end

rule "BAAC 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("CRISIS")==true, treatment_list.isEmpty()==true,  age > 5, string_comorbidities.contains("diabetes")==false, string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, getAsthma().PS>0, getAsthma().PS<3, getAsthma().PEF<80, getAsthma().SAT_O2<94)
    then
        p.addTreatment(Treatment.BAAC_A);
        System.out.println("The patient has to be treated with 0.5-1 mg/kg of BAAC on demand ");
end

rule "BAAC + Sistemic Corticoids 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("CRISIS")==true, treatment_list.isEmpty()==true,  age <= 5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false,
        string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, getAsthma().PS>4, getAsthma().PS<6, getAsthma().PEF<80, getAsthma().SAT_O2>91, getAsthma().SAT_O2<94)
    then
        p.addTreatment(Treatment.BAAC_C);
        p.addTreatment(Treatment.SYSTEMIC_CORTICOIDS_C);
        System.out.println("The patient has to be treated with 0.15-2.5 mg/kg of BAAC combined with 1 mg/kg/day of Sistemic Corticoidsis");
end

rule "BAAC + Sistemic Corticoids 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("CRISIS")==true, treatment_list.isEmpty()==true,  age >5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, 
        string_comorbidities.contains("hypertiroidism")==false, string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, getAsthma().PS>4, getAsthma().PS<6, getAsthma().PEF>60, getAsthma().SAT_O2>91, getAsthma().SAT_O2<94)
    then
        p.addTreatment(Treatment.BAAC_A);
        p.addTreatment(Treatment.SYSTEMIC_CORTICOIDS_A);
        System.out.println("The patient has to be treated with 0.5-1 mg of BAAC on demand combined with 3 mg/kg/day of Sistemic Corticoidsis ");
end

rule "BAAC + Sistemic Corticoids + Suplementary O2 1"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("CRISIS")==true, treatment_list.isEmpty()==true, age >5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, 
        string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, getAsthma().PS>7, getAsthma().PS<9, getAsthma().PEF<60, getAsthma().SAT_O2<91)
    then
        p.addTreatment(Treatment.BAAC_A);
        p.addTreatment(Treatment.SYSTEMIC_CORTICOIDS_A);
        p.addTreatment(Treatment.SUPLEMENTARY_O2);
        System.out.println("The patient has to be treated with 0.5-1 mg of BAAC on demand combined with 3 mg/kg/day of Sistemic Corticoidsis and Suplementary O2 on demand ");
end

rule "BAAC + Sistemic Corticoids + Suplementary O2 2"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("CRISIS")==true, treatment_list.isEmpty()==true, age <=5, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false, 
        string_comorbidities.contains("infecction")==false, string_comorbidities.contains("osteoporosis")==false, string_comorbidities.contains("peptic ulcer")==false, 
        getAsthma().PS>7, getAsthma().PS<9, getAsthma().PEF<60, getAsthma().SAT_O2<91)
    then
        p.addTreatment(Treatment.BAAC_C);
        p.addTreatment(Treatment.SYSTEMIC_CORTICOIDS_C);
        p.addTreatment(Treatment.SUPLEMENTARY_O2);
        System.out.println("The patient has to be treated with 0.15-2.5 mg/kg of BAAC combined with 1 mg/kg/day of Sistemic Corticoidsis and Suplementary O2 on demand ");
end

rule "BAAC on demand Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), p.getAsthma().getStage_string().equalsIgnoreCase("INTERMITTENT")==true ||  p.getAsthma().getStage_string().equalsIgnoreCase("MILD PERSISTENT")==true ||  p.getAsthma().getStage_string().equalsIgnoreCase("MODERATE PERSISTENT")==true || p.getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true, string_comorbidities.contains("diabetes")==false, 
        string_comorbidities.contains("glaucoma")==false, string_comorbidities.contains("cardiovascular disease")==false, string_comorbidities.contains("hypertiroidism")==false)
    then
        
        p.addTreatment(Treatment.BAAC_CRISIS);
        System.out.println("In case there's a crisis during the treatment, the patient has to take 2-4 inhalations of BAAC on demand ");
end

rule "Hospitalization Rule"
    dialect "java"
    when
        p : Patient(getRespiratorydisease().equals("Asthma"), treatment_list.isEmpty()==false, p.getAsthma().getStage_string().equalsIgnoreCase("SEVERE PERSISTENT")==true,treat_stage==6, symptoms_controlled==false)
    then
        p.setHospitalization(true);
        System.out.println("The patient needs to be hospitalized");
end